"""Write DIFFERENCES.md: every parsed-vs-feed difference for the four fixture folders.

    python -m parsers.diff_report [--feed feeds/2026-10-02.json] > DIFFERENCES.md
"""
import argparse
import glob
import os

from .compare import run

RUNS = [
    # No history snapshot comparison: the feed's 2026-09-30 snapshots were put together by hand.
    ("The_Grove", "2026-10-01_0951", "grove", None),
    ("Faculty47", "2026-10-01_0951", "f47", None),
    ("The_Grove", "2026-09-30_1813", "grove", None),
    ("Faculty47", "2026-09-30_1756", "f47", None),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--feed", default="feeds/2026-10-02.json")
    a = ap.parse_args()
    print(f"# Parser output compared with {a.feed}\n")
    print("Generated by `python -m parsers.diff_report`. Each section lists what the parsers read from one fixture folder and where it differs from the feed. Nothing here says which side is right.\n")
    for prop, stamp, pid, snap in RUNS:
        folder = glob.glob(os.path.join("fixtures", f"Command_Center_Reports_-_{prop}_-_{stamp}"))[0]
        diffs, notes = run(folder, pid, a.feed, snap)
        print(f"## {prop.replace('_', ' ')}, export {stamp} ({len(diffs)} differences)\n")
        for n in notes:
            print(f"- note: {n}")
        by = {}
        for s, k, parsed, feed in diffs:
            by.setdefault(s, []).append((k, parsed, feed))
        print()
        for s, items in by.items():
            print(f"### {s}\n")
            print("| item | parsers read | feed has |\n|---|---|---|")
            for k, parsed, feed in items:
                print(f"| {k} | {parsed!r} | {feed!r} |".replace("\n", " "))
            print()


if __name__ == "__main__":
    main()
